matrix:
    include:
        - os: linux
          language: python
          python: "3.6"

before_install:
    - ./travis_setup.sh

script:
    - pip3 install -e .
    - python3 -c "import mujoco_py"
    - python3 -c "import spinup"
    - python3 -m pytest
